### ISSUE TITLE
Logo integrieren (mobile)

### ISSUE THREAD

**Issue by julimage** [julimage/ib-bauwesen#6]
irgendwie sollte das Logo irgendwo auftauchen in der mobilen version... vielleicht, wenn man auf menu drückt, dass es dann unter dem letzten punkt (referenzen) drunter steht. auf das ist sicher auch doof. oder bei dem punkt "kontaklt" integrieren.

**Comment by aschle** [comment]
das logo in der Navigationszeile immer anzeigen auch auf mobil, dann den Balken halt etwas größer machen.

wenn das oben dranscroll, druch text ib-bauwesen ersetzen anstelle von logo, das wird sonst zu klein.

konstent machen.
